- src/psycop/model_evaluation/binary/utils.py
2 edits:
* `n_bootstraps`: Required for plots to take less than 10 minutes per plot. Also, acceptable according to:
> "An Introduction to the Bootstrap" (1994) by Efron and Tibshirani, they report that you can get a decent estimate with B=25, and B=200 you approach a similar coefficient of variation as infinity. They provide a table of the coefficients of variation for various B (p. 52-53, both pages are available on google books).
* Added a try/except to `metric_wrapper`
For e.g. `roc_auc_by_hour_of_day`, some of the resampled datasets included only one class for true values (i.e. only negatives), and as such, `roc_auc` was undefined. In those cases, return `np.nan`. Makes for some somewhat ugly figures:
But I don't see how else to fix it. Any suggestions, @KennethEnevoldsen? :-)
> feat: enable bootstrap to handle only one class

- src/psycop/common/model_evaluation/markdown/md_objects.py
- src/psycop/common/model_evaluation/markdown/test_md_objects.py
- src/psycop/projects/t2d/paper_outputs/aggregate_eval/single_pipeline_full_eval.py
- src/psycop/projects/t2d/paper_outputs/aggregate_eval/supplementary_full_eval.py
- src/psycop/projects/t2d/paper_outputs/dataset_description/describe_features.py
- tasks.py
@HLasse, would strongly prefer a full review of:
`src/psycop/common/model_evaluation/markdown/md_objects.py`
`src/psycop/common/model_evaluation/markdown/test_md_objects.py`
if possible :-)
Fixes #76 if merged.
> feat: add markdown handler to common

- psycop/common/feature_generation/application_modules/generate_feature_set.py
As discussed. 
Moved check for whether you want to overwrite files in the `feature_set_dir` path. Now it is checked before the feature generation is executed so that we will not potentially generate features that we would not want to save
> feat: move feature_set_dir check to earlier 

- .gitignore
- .vscode/tasks.json
- tasks.py
Hi everyone!
The next time you pull, you can run a command equivalent to `inv pr` by running:
In the VSCode command palette. Should make things even smoother 👍
> feat: add vscode PR task

- psycop/common/sequence_models/embedders/BEHRT_embedders.py
- psycop/common/sequence_models/tests/test_embedding.py
Noticed that we lose a lot of diagnoses when mapping from ICD-10 to CALIBER (~40% of patients have empty sequences after mapping).
CALIBER uses ICD-10 with three or four characters (e.g. "A20" and "A201").
Before, get_mapped_diagnoses_codes() matches the codes directly and if they do not exist in the mapping, it excludes them. Changed this so that it checks different levels of granularity, starting with the highest. (e.g. for "A201" it first checks for "A201" in the mapping and if that does not exist it checks for "A20" and then uses that, otherwise excludes it).
Now, only ~10% of patients have empty sequences after mapping.
> feat: allow levels of granularity in diagnosis mapping

- Dockerfile
This saves pip's cache so it can be used across rebuilds, dramatically improving performance on rebuild 👍
> dev: use docker buildkit cache for pip

- .gitignore
- tasks.py
This adds an entrypoint for running tests using https://testmon.org/
> pytest-testmon is a pytest plugin which selects and executes only tests you need to run. It does this by collecting dependencies between tests and all executed code (internally using Coverage.py) and comparing the dependencies against changes. testmon updates its database on each test execution, so it works independently of version control.
This dramatically decreases our test run times, especially for a monorepo.
Potential downsides are false negatives. To avoid this, we still run the full test suite in CI.
I've added it as a separate entrypoint so we can test it, before suggesting it as an integration in everyone's workflow.  This is tracked in #390, so we don't forget.
Since it uses code coverage, it won't catch if …
> dev: add quick PR using testmon

- .vscode/settings.json
- psycop/common/model_training_v2/config/historical_registry_configs/preprocessing/prefix_count_validator/prefix_count_validator_20231117_092246.cfg
- psycop/common/model_training_v2/config/populate_registry.py
- psycop/common/model_training_v2/config/registries_testing_utils.py
- psycop/common/model_training_v2/trainer/preprocessing/steps/column_validator.py
- psycop/common/model_training_v2/trainer/preprocessing/steps/test_v2_filters.py
- requirements.txt
- Fixes #435
Ensuring that the correct columns are passed seems like a concern for the dataloaders. However, we probably want to validate it anyway, since messing up here could mean big trouble. I've added a simple preprocessing validation step to check for it.
> feat: ensure appropriate number of outcome columns

- psycop/common/sequence_models/embedders/BEHRT_embedders.py
- psycop/common/sequence_models/tests/test_embedding.py
- psycop/common/sequence_models/train.py
1. Rename `filter_events` to `A_diagnoses_only` to convey content. This makes it less general; if we want to avoid that, perhaps we should conform to a `Protocol`?
2. Add documentation of Caliber codes
> docs: minor renames in behrt

- psycop/automation/environment.py
- setup_overtaci.sh
- tasks.py
@HLasse, @bokajgd FYI, no need to review if you don't want to.
Currently, running `inv install-requirements` on Ovartaci overrides torch with a version that does not have CUDA compiled. This is obviously a problem.
I tried getting it back into a consistent state by running `setup_ovartaci.sh`:
```bash
conda install pytorch=2.1.0 pytorch-cuda=12.1 -c https://exrhel0371.it.rm.dk/api/repo/pytorch -c https://exrhel0371.it.rm.dk/api/repo/nvidia -c https://exrhel0371.it.rm.dk/api/repo/anaconda --override-channels --insecure -y
```
But that did not solve the problem.
* Moved all the handling into `inv install-requirements`, so we only have one entrypoint.
* Added `--force-reinstall` to the conda command, since that overrides the pip-installed torch with torch compiled for CUDA.
Fixes #552.
> dev: add pytorch deps to `inv install`

- psycop/common/feature_generation/sequences/patient_loaders.py
- psycop/common/sequence_models/config_schema.py
- psycop/common/sequence_models/logger.py
- psycop/common/sequence_models/registry.py
- psycop/common/sequence_models/tests/test_config.cfg
- psycop/common/sequence_models/train.py
- psycop/projects/sequence_models/pretrain_behrt.cfg
- psycop/projects/sequence_models/pretrain_mini_behrt.cfg
For #560, I needed the path of the pretrained model. However, I think it is on your user account (ADMINKEN**) @KennethEnevoldsen.
So, wanted to run a new pretraining that saves to a dir on `E:/shared_resources`, and might as well add mlflow at the same time.
* Unified logger interfaces, to make it easier to change between them
* Added mlflow logger
Started a training, but failed because of the MLflow server being down. More info here: https://github.com/Aarhus-Psychiatry-Research/psycop-ml-ops/issues/54
Also fixes #562.
> feat: pretrain with `mlflow`

- psycop/common/feature_generation/sequences/cohort_definer_to_prediction_times.py
- psycop/common/feature_generation/sequences/patient_loaders.py
- psycop/common/feature_generation/sequences/patient_slice_getter.py
- psycop/common/feature_generation/sequences/test_event_dataframes_to_patient.py
- psycop/common/feature_generation/sequences/test_patient_loaders.py
- psycop/projects/sequence_models/pretrain.py
Move filtering of patients by minimum number of events to the loading of patients, rather than the loading of events. Makes more semantic sense IMO.
> refactor: move min_n_visits filtering to PatientLoader

- psycop/projects/sequence_models/pretrain.py
- psycop/projects/sequence_models/pretrain_behrt.cfg
Importing the Registry worked in a sample of other files in the repo, so there must be some circular importation going on here.
However, we don't need the registry import anymore due to decomposition of the dataset. The current pretrain runs on Ovartaci, so I think it's OK for now.
Fixes #582.
> feat: ready for pretraining

- psycop/common/global_utils/config_utils.py
- psycop/common/model_training_v2/loggers/mlflow_logger.py
Mlflow does not allow @ and * when logging params. Changed the values to "" and "_" instead. Added the name of the run-id to tmp path to avoid potential conflicts during parallel runs. 
Merged, but feel free to post review
> fix: replace disallowed symbols in config before logging to mlflow

- psycop/common/feature_generation/application_modules/save_dataset_to_disk.py
- psycop/common/feature_generation/loaders/raw/load_ids.py
- psycop/common/feature_generation/loaders/raw/load_text.py
- psycop/common/feature_generation/sequences/patient_loader.py
- psycop/common/model_training_v2/trainer/data/data_filters/geographical_split/make_geographical_split.py
- psycop/common/model_training_v2/trainer/data/data_filters/geography.py
- psycop/common/model_training_v2/trainer/data/data_filters/original_ids.py
- pyproject.toml
Adds a `split` column to the regional split dataframe for easy integration with other loaders. Added a function for loading either the original splits or the regional splits.
> feat: joint id loader

- .vscode/tasks.json
- psycop/common/model_training_v2/trainer/data/dataloaders.py
- psycop/common/model_training_v2/trainer/preprocessing/steps/column_validator.py
- psycop/common/types/test_validated_frame.py
- psycop/common/types/validated_frame.py
- psycop/common/types/validator_rules.py
- requirements.txt
Fixes #622.
I propose we use this for:
* CohortDefiner's return type
* SplitLoader's return type
* Others?
This ensures that modules which return frames conform to the same return type contract, so they can be swapped interchangeably.
Ignore anything not in the `types` folder, they are just an updated of `functionalpy` to `iterpy`.
> feat: ValidatedFrame when we need to return frames

- psycop/common/model_training_v2/trainer/data/data_filters/geography.py
Helps in that:
1. Registry resolution is faster, since it does not need to wait on loading
2. Registry resolution can happen in tests, since it does not need access to the SQL database. Required for #638.
> fix: `RegionalFilter` should not load at init

- psycop/common/model_training_v2/config/test_unpack_annotations.py
- psycop/common/model_training_v2/config/unpack_annotations.py
> fix: literal type hint parsing

- psycop/common/feature_generation/loaders/raw/load_ids.py
- psycop/common/model_training_v2/trainer/preprocessing/steps/geographical_split/_geographical_split.py
- psycop/common/model_training_v2/trainer/preprocessing/steps/geographical_split/test_geographical_split.py
- psycop/common/model_training_v2/trainer/preprocessing/steps/row_filter_split.py
- psycop/projects/scz_bp/data_inspection/scz_bp_age_at_outcome.py
- psycop/projects/scz_bp/data_inspection/scz_bp_time_of_first_contact_to_outcome.py
- psycop/projects/scz_bp/dataset_description/scz_bp_table_one.py
Fixes #658.
@HLasse I've type-ignored the places where you use the private function. This could probably be fixed by using the `RegionalFilter`, and would be a good example to set when others look at your code as well. That said, up to you 👍
> refactor: hide geographical split loading inside the `RegionalSplit` class

- .vscode/tasks.json
I've disabled type checks when running through `tasks.json` – it is _much_ faster to look whether there are any problems in the problems tab.
I don't have a strong opinion on this, so open to suggestions @HLasse 👍
> dev: make default build task idempotent

- psycop/common/feature_generation/loaders/raw/load_ids.py
> fix: correct types for id col in splitframe

- psycop/common/model_training_v2/config/historical_registry_configs/preprocessing/quarantine_filter/quarantine_filter_20240115_120142.cfg
- psycop/common/model_training_v2/trainer/preprocessing/steps/row_filter_other.py
- psycop/common/model_training_v2/trainer/preprocessing/steps/test_row_filters.py
When using the quarantine filter in cohort definers, the pred times have not had uuids generated yet. We probably don't want that as a requirement, so instead, we can generate a tmp uuid for this filter. Let me know what you think 👍
> feat(#709): support temporary uuid in quarantine filter

- psycop/common/feature_generation/sequences/event_loader.py
- psycop/common/feature_generation/sequences/patient_loader.py
- psycop/common/feature_generation/sequences/patient_slice_collater.py
- psycop/common/feature_generation/sequences/prediction_time_collater.py
- psycop/common/sequence_models/aggregators.py
- psycop/common/sequence_models/callbacks.py
- psycop/common/sequence_models/config_utils.py
- psycop/common/sequence_models/embedders/BEHRT_embedders.py
- psycop/common/sequence_models/logger.py
- psycop/common/sequence_models/model_layers.py
- psycop/common/sequence_models/optimizers.py
- psycop/common/sequence_models/registry.py
- psycop/common/sequence_models/tasks/patientslice_classifier.py
- psycop/common/sequence_models/tasks/pretrainer_behrt.py
- psycop/common/sequence_models/tests/test_finetuning.py
- psycop/common/sequence_models/tests/test_train.py
- psycop/projects/sequence_models/finetune_t2d.py
- psycop/projects/t2d/feature_generation/cohort_definition/t2d_cohort_definer.py
Makes it easier to separate from the baseline registry. Was indicated for registering the new regionalsplitfilter within a scope accessible by the sequence models (used in #716). 
Hope it's OK with you @KennethEnevoldsen?
I wonder why that's necessary, though. Not sure I quite understand the namespacing of registries. Would love a chat about it if you have time @KennethEnevoldsen.
> refactor: rename registry to SequenceRegistry

- psycop/common/model_training_v2/config/historical_registry_configs/preprocessing/baseline_preprocessing_pipeline/baseline_preprocessing_pipeline-20231115_120000.cfg
- psycop/common/model_training_v2/config/historical_registry_configs/trainers/crossval_trainer/crossval_trainer-20231511-120000.cfg
- psycop/common/model_training_v2/config/historical_registry_configs/trainers/split_trainer/split_trainer-20231511-120000.cfg
- psycop/common/model_training_v2/hyperparameter_suggester/test_optuna_hyperparameter_search.cfg
- psycop/common/model_training_v2/trainer/preprocessing/pipeline.py
> fix: baselinelogger should not default to None

- .devcontainer/devcontainer.json
- .devcontainer/post-start.sh
- .vscode/tasks.json
- Dockerfile
- dev-requirements.txt
- lefthook.yml
Just want to show this tool off, and then we can discuss whether we want to add it.
Upside:
* Auto-stage changes on fix! Means we can lint on commit. No more manual pre-commit runs.
Main uncertainties:
* Can it run on Ovartaci?
* No, it requires a download via either `brew`, `go` or `npm`
* Users running linting should use `inv lint`
* How does it handle cases where the linter cannot fix it if `stage_fixed = True`? Should we run the linter twice to get errors?
* It fails correctly
@HLasse, @KennethEnevoldsen, initial thoughts? Think we'll loop in the others if we don't outright reject it.
This would be a good time to migrate as much as possible out of pre-commit as well, i.e. removing black.
> dev: autofix on commit with lefthook

- .github/workflows/lint.yml
- .github/workflows/modified_shared_files.yml
> ci: disable concurrency checks to avoid false cancellations

- psycop/common/model_training_v2/trainer/preprocessing/steps/column_validator.py
> fix: ensure expectation counts are recast to int

- psycop/common/model_training_v2/trainer/cross_validator_trainer.py
> fix(#775): log outcome column as string, not Index

- psycop/common/model_training_v2/trainer/task/estimator_steps/lightgbm.py
- psycop/common/model_training_v2/trainer/task/estimator_steps/logistic_regression.py
- psycop/common/model_training_v2/trainer/task/estimator_steps/xgboost.py
This ensures that when we want to extract e.g. feature importance from the models, they will always be found under `pipeline.named_steps["classifier"]` instead of being the name of the model. Requires us to follow the naming convention when/if adding additional classification models, but no further downsides as I see it
> feat: unify naming classification model steps

- dev-requirements.txt
A htop-like tool that also works on Windows.
On Ovartaci, I had to manually create a file for it to run. Seems we might not have write-permissions for sub-directories of `\Local\Temp`:
```python
from pathlib import Path
if __name__ == "__main__":
user = "adminmanber"
dir = Path(f"C:/Users/{user}/AppData/Local/Temp/glances-onerm/")
dir.mkdir(exist_ok=True)
(dir / f"{user}.log").write_text("")
```
@HLasse You might find this interesting! If it passes security-checks, it could make it much easier to check if others are running something before starting one's own job.
> build(deps): add glances

- psycop/common/model_training_v2/config/baseline_pipeline.py
@HLasse Post-merge review. When programatically changing configs, recommend we use `train_baseline_model_from_cfg`. Was the cause of my confusion in #907.
> refactor: ensure logging when training from mutated cfg

- psycop/common/model_training_v2/trainer/preprocessing/steps/row_filter_other.py
- psycop/common/model_training_v2/trainer/preprocessing/steps/test_row_filters.py
Fixes #1008 
Note @bokajgd @erikperfalk @sarakolding if you have used `QuarantineFilter` to remove e.g. incident cases in the last X years, if the outcome happened on the same day as a prediction time they were not filtered. Probably not major (in my case, approximately 200 prediction times that should have been removed)
> fix: `QuarantineFilter` does not remove prediction times on same day

- .snyk
Ignores:
- `SNYK-PYTHON-TRANSFORMERS-8400823`
- `SNYK-PYTHON-TRANSFORMERS-8400822`
- `SNYK-PYTHON-TRANSFORMERS-8400820`
Discussed and approved in Slack conversation on the 3/12/24 in the Programming channel.
> chore: ignore snyk vulnerabilities for transformers

- psycop/common/model_training_v2/config/historical_registry_configs/preprocessing/lookbehind_combination_col_filter/lookbehind_combination_col_filter-20231115-120000.cfg
- psycop/common/model_training_v2/trainer/preprocessing/steps/column_filters.py
- psycop/common/model_training_v2/trainer/preprocessing/steps/test_column_filters.py
when selecting a combination of lookbehinds, we were selecting only based on integers - meaning if you were trying to select predictors with lookbehinds of 1, you would not only get within_1_days, but also within_10_days or even f1_disorders
> fix: lookbehind combination col filter
