Aarhus-Psychiatry-Research/psycop-common

src/psycop/common/model_evaluation/confusion_matrix/confusion_matrix.py, src/psycop/common/model_evaluation/confusion_matrix/test_confusion_matrix.py, src/psycop/common/model_evaluation/patchwork/patchwork_grid.py, src/psycop/common/test_utils/str_to_df.py, src/psycop/projects/t2d/paper_outputs/model_description/performance/plotnine_confusion_matrix.py, src/psycop/projects/t2d/paper_outputs/model_description/performance/test_plotnine_confusion_matrix.py, tasks.py
Created a confusion matrix, and abstracted it into common.
@HLasse, please review the code in common, and feel free to add commons on the code in t2d :-)
For T2D, needed something that was a plotnine plot so I can use it with patchworklib.
Unfortunately, `matplotlib` does not allow moving the x-axis on the top of the plot, so quite limited in the options here.
Output:
=> feat: plotnine confusion matrix

src/psycop/common/model_evaluation/binary/global_performance/roc_auc.py, src/psycop/common/model_evaluation/binary/global_performance/test_global_performance_plots.py, src/psycop/projects/t2d/paper_outputs/model_description/performance/roc_auc_pipeline.py
Just to let you guys know that I've converted it, feel free to add comments if you'd like something chanegd :-)
=> feat: convert auroc to plotnine

src/psycop/common/model_training/preprocessing/pre_split/processors/row_filter.py
=> fix: correct lookbehind selection

.gitignore, src/psycop/common/model_evaluation/patchwork/patchwork_grid.py, src/psycop/common/model_evaluation/patchwork/test_patchwork_grid.py, src/psycop/projects/t2d/feature_generation/eligible_prediction_times/loader.py, src/psycop/projects/t2d/model_training/run_performance_in_group.py, src/psycop/projects/t2d/paper_outputs/aggregate_eval/single_pipeline_full_eval.py, src/psycop/projects/t2d/paper_outputs/aggregate_eval/supplementary_full_eval.py, src/psycop/projects/t2d/paper_outputs/config.py, src/psycop/projects/t2d/paper_outputs/dataset_description/describe_features.py, src/psycop/projects/t2d/paper_outputs/dataset_description/hba1c_within_lookahead.py, src/psycop/projects/t2d/paper_outputs/model_description/feature_importance/gain/gain_table.py, src/psycop/projects/t2d/paper_outputs/model_description/performance/incidence_by_time_until_diagnosis.py, src/psycop/projects/t2d/paper_outputs/model_description/performance/performance_by_ppr.py, src/psycop/projects/t2d/paper_outputs/model_description/performance/plotnine_confusion_matrix.py, src/psycop/projects/t2d/paper_outputs/model_description/performance/sensitivity_by_time_to_event_pipeline.py, src/psycop/projects/t2d/paper_outputs/model_description/performance/test_plotnine_confusion_matrix.py, src/psycop/projects/t2d/paper_outputs/model_description/robustness/robustness_plot.py, src/psycop/projects/t2d/paper_outputs/model_permutation/boolean_features.py, src/psycop/projects/t2d/paper_outputs/model_permutation/only_hba1c.py, src/psycop/projects/t2d/paper_outputs/model_permutation/test_only_hba1c.py, src/psycop/projects/t2d/paper_outputs/model_selection/performance_by_lookahead_by_model_type.py, src/psycop/projects/t2d/paper_outputs/run_pipeline_on_train.py, src/psycop/projects/t2d/paper_outputs/selected_runs.py, src/psycop/projects/t2d/paper_outputs/utils/test_plotnine_theme.py
=> feat: new training run

src/psycop/common/feature_generation/data_checks/flattened/feature_describer.py
=> feat: simplify feature describer

.coveragerc, .github/workflows/check_for_rej.yml, .github/workflows/cruft.yml, .github/workflows/tests.yml, .github/workflows/tests_post_coverage_comment.yml, .gitignore
=> ci: try coverage comment with diff

.coveragerc, src/psycop/common/model_evaluation/binary/performance_by_ppr/prop_of_all_events_hit_by_true_positive.py, src/psycop/common/model_evaluation/binary/performance_by_ppr/test_performance_by_ppr.py
=> feat: check test coverage

src/psycop/common/minimal_pipeline.py, src/psycop/common/test_e2e.py
=> feat: create minimal pipeline

src/psycop/common/model_evaluation/markdown/md_objects.py, src/psycop/common/model_evaluation/markdown/test_md_objects.py, src/psycop/projects/t2d/paper_outputs/aggregate_eval/single_pipeline_full_eval.py, src/psycop/projects/t2d/paper_outputs/aggregate_eval/supplementary_full_eval.py, src/psycop/projects/t2d/paper_outputs/dataset_description/describe_features.py
=> ignore: highlight coverage error

src/psycop/projects/forced_admission_inpatient/model_training/config/project/default_project.yaml, src/psycop/projects/forced_admission_inpatient/model_training/train_model_from_application_module.py
Fixed project_path for project/forced_admissions_inpatient
=> Fix: project_path in model training

.github/workflows/check_for_rej.yml, .github/workflows/static_type_checks.yml, .github/workflows/tests.yml, .gitignore, pyproject.toml, tasks.py
=> ci: remove tox and docs

src/psycop/projects/forced_admission_inpatient/model_evaluation/application/pipelines/feature_importance/gain_pipeline.py, src/psycop/projects/forced_admission_inpatient/model_evaluation/application/pipelines/feature_importance/shap_dependency_pipeline.py, src/psycop/projects/forced_admission_inpatient/model_evaluation/application/pipelines/feature_importance/shap_summary_pipeline.py, src/psycop/projects/forced_admission_inpatient/model_evaluation/figures/feature_importance/shap/get_shap_values.py, src/psycop/projects/forced_admission_inpatient/model_evaluation/figures/feature_importance/shap/shap_plots.py
=> feat: add shap/gain to model eval

src/psycop/common/model_evaluation/utils.py, src/psycop/projects/forced_admission_inpatient/model_evaluation/best_runs.py, src/psycop/projects/forced_admission_inpatient/model_evaluation/config.py, src/psycop/projects/forced_admission_inpatient/model_evaluation/data/load_true_data.py, src/psycop/projects/forced_admission_inpatient/model_evaluation/figures/feature_importance/gain_plot.py, src/psycop/projects/forced_admission_inpatient/model_evaluation/figures/feature_importance/shap/get_shap_values.py
Minor utility function for finding best model.
=> feat: add find_best_run_in_dir function to model eval

src/psycop/common/model_training/training/train_and_predict.py
=> feat: add print statement for oof auc score during crossvalidation

src/psycop/projects/forced_admission_inpatient/model_evaluation/application/pipelines/performance/sensitivity_by_time_to_event.py, src/psycop/projects/forced_admission_inpatient/model_evaluation/config.py, src/psycop/projects/forced_admission_inpatient/model_evaluation/dataset_description/utils.py, src/psycop/projects/forced_admission_inpatient/model_training/config/default_config.yaml, src/psycop/projects/forced_admission_inpatient/model_training/config/model/logistic-regression.yaml, src/psycop/projects/forced_admission_inpatient/model_training/config/preprocessing/default_preprocessing.yaml
Adding sensitivity by days to outcome, binned in month-long intervals
=> fa: Adding sensitivity by days to outcome

tasks.py
=> build: avoid spending all the time on processes when running on Ovartaci

.vscode/launch.json, .vscode/settings.json, application/test_imports.py
=> build: add vscode env settings

tasks.py
=> build: update inv install

psycop/common/feature_generation/application_modules/describe_flattened_dataset.py, psycop/common/feature_generation/application_modules/filter_prediction_times.py, psycop/common/feature_generation/application_modules/flatten_dataset.py, psycop/common/feature_generation/data_checks/flattened/data_integrity.py, psycop/common/feature_generation/data_checks/flattened/feature_describer.py, psycop/common/feature_generation/data_checks/raw/check_predictor_lists.py, psycop/common/feature_generation/data_checks/raw/check_raw_df.py, psycop/common/feature_generation/data_checks/raw/validate_raw_data.py, psycop/common/feature_generation/data_checks/utils.py, psycop/common/feature_generation/loaders/filters/diabetes_filters.py, psycop/common/feature_generation/loaders/flattened/local_feature_loaders.py, psycop/common/feature_generation/loaders/non_numerical_coercer.py, psycop/common/feature_generation/loaders/raw/load_diagnoses.py, psycop/common/feature_generation/loaders/raw/load_ids.py, psycop/common/feature_generation/loaders/raw/load_structured_sfi.py, psycop/common/feature_generation/loaders/raw/load_text.py, psycop/common/feature_generation/utils.py, psycop/common/model_training/tests/test_performance_by_threshold.py, psycop/projects/care_ml/model_evaluation/application/pipelines/feature_importance/shap_summary_pipeline.py, psycop/projects/forced_admission_inpatient/model_evaluation/application/pipelines/feature_importance/shap_summary_pipeline.py, pyproject.toml
=> feat: add TCH ruff rules

psycop/common/feature_generation/loaders/raw/load_structured_sfi.py
Added a few extra loaders for temporary leave, upon Andreas' request
=> add "temporary leave" loader for sfi

psycop/common/feature_generation/application_modules/flatten_dataset.py
=> fix: add birthdays as default

.gitignore, .vscode/settings.json
=> Include gitignore files in explorer

psycop/common/model_training/preprocessing/pre_split/processors/col_filter.py
add custom outcome prefix from cfg to col filter function
=> allows custom outcome prefix

psycop/projects/restraint/cohort_creation/pipelines/cut_off_days.py, psycop/projects/restraint/cohort_creation/utils/utils.py, psycop/projects/restraint/feature_generation/main.py, psycop/projects/restraint/feature_generation/modules/loaders/load_coercion_df_with_prediction_times_and_outcome.py, psycop/projects/restraint/feature_generation/modules/specify_features.py, psycop/projects/restraint/feature_generation/modules/specify_text_features.py, psycop/projects/restraint/model_training/application/config/data/default_data.yaml, psycop/projects/restraint/model_training/application/config/project/default_project.yaml, psycop/projects/restraint/model_training/application/train_model_e2e.py
=> additional features for restraint project

psycop/projects/t2d/paper_outputs/aggregate_eval/supplementary_full_eval.py
=> feat: change prefix for supplementary outputs

psycop/common/feature_generation/loaders/raw/load_medications.py
Added some extra loaders for medications, as per Andreas' request :-)
=> add additional medication loaders

.vscode/settings.json, psycop/common/feature_generation/loaders/raw/load_visits.py, psycop/common/model_training/training_output/dataclasses.py, psycop/common/model_training/training_output/test_dataclasses.py, psycop/projects/scz_bp/evaluation/configs.py, psycop/projects/scz_bp/evaluation/model_performance/performance/performance_by_time_to_event.py, psycop/projects/scz_bp/evaluation/model_performance/robustness/scz_bp_robustness_by_age.py, psycop/projects/scz_bp/evaluation/model_performance/robustness/scz_bp_robustness_by_calendar_time.py, psycop/projects/scz_bp/evaluation/model_performance/robustness/scz_bp_robustness_by_cyclic_time.py, psycop/projects/scz_bp/evaluation/model_performance/robustness/scz_bp_robustness_by_sex.py, psycop/projects/scz_bp/evaluation/model_performance/robustness/scz_bp_robustness_by_time_from_first_visit.py, psycop/projects/scz_bp/evaluation/model_performance/robustness/scz_bp_robustness_plot.py, psycop/projects/scz_bp/evaluation/model_selection/performance_by_group_lookahead_model_type.py, psycop/projects/scz_bp/evaluation/pipeline_objects.py, psycop/projects/scz_bp/feature_generation/specify_features.py, psycop/projects/t2d/paper_outputs/model_description/robustness/robustness_by_time_from_first_visit.py
=> Misc eval for scz bp 

psycop/projects/forced_admission_inpatient/feature_generation/main.py, psycop/projects/forced_admission_inpatient/feature_generation/modules/specify_features.py
Is there a better name than sparse_feature_set? I avoided baseline/base as this could maybe be confused with "baseline models".
=> added function to create sparse_feature_set

psycop/common/feature_generation/text_models/encode_text_as_tfidf_scores.py, psycop/common/feature_generation/text_models/utils.py
=> feat: learn and save tfidf encodings for feature generation

.github/workflows/static_type_checks.yml, README.md
Just added an extra line to readme local instructions to clarify how to use invoke
=> fix: instructions in README.md

psycop/common/feature_generation/application_modules/describe_flattened_dataset.py, psycop/common/feature_generation/application_modules/flatten_dataset.py, psycop/common/feature_generation/application_modules/generate_feature_set.py, psycop/common/feature_generation/application_modules/save_dataset_to_disk.py, psycop/common/minimal_pipeline.py, psycop/common/test_e2e.py, psycop/projects/cancer/feature_generation/main.py, psycop/projects/forced_admission_inpatient/feature_generation/main.py, psycop/projects/restraint/feature_generation/main.py
Allows user to specify specific feature set name when generating features
=> Update flattened df save pipeline and dir

.github/workflows/tests.yml
=> ci: add coverage annotations

psycop/common/data_structures/patient.py, psycop/common/data_structures/static_feature.py, psycop/common/data_structures/temporal_event.py, psycop/common/data_structures/test_patient.py, psycop/common/feature_generation/sequences/event_dataframes_to_patient.py, psycop/common/feature_generation/sequences/test_event_dataframes_to_patient.py, psycop/common/feature_generation/sequences/utils_for_testing.py
=> feat: add date of birth active record

psycop/projects/forced_admission_inpatient/feature_generation/modules/loaders/load_forced_admissions_dfs_with_prediction_times_and_outcome.py
=> small type error fix

psycop/projects/forced_admission_inpatient/model_eval/model_description/performance/sensitivity_by_time_to_event.py, psycop/projects/forced_admission_inpatient/model_eval/run_pipeline_on_val.py
=> add fa_sensitivity_by_time_to_event

psycop/projects/forced_admission_inpatient/model_eval/config.py, psycop/projects/forced_admission_inpatient/model_eval/model_description/performance/confusion_matrix_pipeline.py, psycop/projects/forced_admission_inpatient/model_eval/model_description/performance/plotnine_confusion_matrix.py
=> added confusion matrix for fa project

psycop/common/sequence_models/tests/test_main.py, psycop/projects/t2d/paper_outputs/intervention_eval/hba1c.py, psycop/projects/t2d/paper_outputs/intervention_eval/test_hba1c.py, psycop/projects/t2d/paper_outputs/selected_runs.py, psycop/projects/t2d/utils/pipeline_objects.py
=> feat: time from first positive prediction to next hba1c

psycop/projects/forced_admission_inpatient/model_eval/model_description/performance/performance_by_ppr.py
=> added performance by ppr to fa project

psycop/projects/forced_admission_inpatient/feature_generation/main.py, psycop/projects/forced_admission_inpatient/feature_generation/modules/specify_features.py
=> Fa  add 180 lookbehind mean agg

.dockerignore, .github/workflows/static_type_checks.yml, Dockerfile.dev, dev-requirements.txt, pyproject.toml, tasks.py
Adding a development container as an option; should be especially helpful when e.g. @sarakolding gets her new mac.
@HLasse @KennethEnevoldsen Just wanted to show this off - let me know if you want to chat about it 👍
=> ci: add dev container

psycop/common/data_structures/patient.py, psycop/common/feature_generation/application_modules/save_dataset_to_disk.py, psycop/common/feature_generation/loaders/raw/load_ids.py, psycop/common/feature_generation/loaders/raw/load_text.py, psycop/common/feature_generation/sequences/cohort_definer_to_prediction_times.py, psycop/common/feature_generation/sequences/patient_loaders.py, psycop/common/feature_generation/text_embeddings/train_sentence_transformers.py, psycop/common/feature_generation/text_models/preprocessing.py, psycop/common/global_utils/cache.py, psycop/projects/sequence_models/train.py, requirements.txt
=> feat: test sequence prediction time generator

psycop/common/model_training/preprocessing/pre_split/processors/col_filter.py
=> fix outcome col prefix

psycop/common/sequence_models/embedders/BEHRT_embedders.py, psycop/common/sequence_models/tests/conftest.py, psycop/common/sequence_models/tests/test_embedding.py
Added filtering of diagnosis subtypes so we only keep A-diagnoses.
=> feat: filter diagnosis subtype in BEHRT

psycop/common/feature_generation/sequences/cohort_definer_to_prediction_times.py, psycop/common/feature_generation/sequences/patient_loaders.py, psycop/common/feature_generation/sequences/test_patient_loaders.py, psycop/projects/sequence_models/train.py
=> sequence preprocessing

gpu-requirements.txt
=> docs: how to install cuda enabled pytorch on overtaci

psycop/common/model_training/application_modules/trainer_spawner.py, psycop/common/model_training/config_schemas/data.py, psycop/common/model_training/data_loader/data_loader.py, psycop/common/model_training/data_loader/tests/conftest.py, psycop/common/model_training/data_loader/tests/test_data_loader.py, psycop/common/model_training/data_loader/tests/test_feature_merging.py, psycop/common/model_training/data_loader/utils.py, psycop/projects/cancer/model_training/train_models_in_parallel.py, psycop/projects/t2d/paper_outputs/model_permutation/modified_dataset.py
If one specifies multiple paths in `DataSchema.dir` the dataloader will now merge them. This allows us to build upon datasets with by incrementally adding features (without too much hacking). Fixes #277
=> feat: merge feature sets

psycop/common/feature_generation/loaders/raw/load_structured_sfi.py
=> feat: add smoking loaders

psycop/common/sequence_models/aggregators.py, psycop/common/sequence_models/embedders/BEHRT_embedders.py, psycop/common/sequence_models/tests/test_encoder_for_clf.py, psycop/projects/sequence_models/fine_tune.py
=> Add cls token to BEHRT embedder

.devcontainer/devcontainer.json, CHANGELOG.md, dev-requirements.txt, psycop/common/feature_generation/loaders/example/debug_loader_function.py, psycop/common/feature_generation/loaders/example/load_bmi.py, psycop/common/model_evaluation/binary/subgroup_data.py, psycop/common/model_evaluation/binary/time/timedelta_data.py, psycop/common/model_training/preprocessing/pre_split/processors/value_cleaner.py, psycop/common/model_training/training_output/dataclasses.py, psycop/common/test_utils/test_data/model_eval/generate_synthetic_dataset_for_eval.py, psycop/projects/forced_admission_inpatient/model_eval/model_description/performance/sensitivity_by_time_to_event.py, psycop/projects/forced_admission_inpatient/utils/synth_data.py, psycop/projects/restraint/cohort_creation/utils/utils.py, psycop/projects/restraint/model_evaluation/application/pipelines/performance/mcc_pipeline.py, psycop/projects/restraint/model_evaluation/application/pipelines/performance/sensitivity_by_ppr.py, psycop/projects/restraint/model_evaluation/application/pipelines/performance/sensitivity_by_time_to_event.py, psycop/projects/restraint/model_evaluation/application/pipelines/robustness/robustness_by_calendar_time.py, psycop/projects/restraint/model_evaluation/application/pipelines/robustness/robustness_by_cyclic_time.py, psycop/projects/restraint/utils/synth_data.py, psycop/projects/scz_bp/evaluation/model_performance/robustness/scz_bp_robustness_by_calendar_time.py, psycop/projects/scz_bp/evaluation/model_performance/robustness/scz_bp_robustness_by_cyclic_time.py, psycop/projects/t2d/paper_outputs/model_description/performance/sensitivity_by_time_to_event_pipeline.py, psycop/projects/t2d/paper_outputs/model_description/robustness/robustness_by_calendar_time.py, psycop/projects/t2d/paper_outputs/model_description/robustness/robustness_by_cyclic_time.py, pyproject.toml, requirements.txt
* Add pandas-stubs to deps since Pylance bundles them
* Update numpy, since required for pandas-stubs
* Add postStartCommand to devcontainer, to ensure versions are aligned
* Fix the new errors
=> feat: pylance pyright alignment

tasks.py
=> ci: do not fail if pr could not be created

tasks.py
- ibid.
- misc.
- dev: push before PR creation Fixes #301
=> dev: push before PR creation

psycop/projects/clozapine/feature_generation/cohort_definition/clozapine_cohort_definition.py, psycop/projects/clozapine/feature_generation/cohort_definition/eligible_prediction_times/add_age.py, psycop/projects/clozapine/feature_generation/cohort_definition/eligible_prediction_times/eligible_config.py, psycop/projects/clozapine/feature_generation/cohort_definition/eligible_prediction_times/schizophrenia_diagnosis.py, psycop/projects/clozapine/feature_generation/cohort_definition/eligible_prediction_times/single_filters.py, psycop/projects/clozapine/feature_generation/cohort_definition/outcome_specification/first_clozapine_prescription.py, psycop/projects/clozapine/feature_generation/main.py, psycop/projects/clozapine/feature_generation/modules/specify_features.py, psycop/projects/clozapine/feature_generation/modules/specify_text_features.py, psycop/projects/clozapine/feature_generation/modules/text_model_pipelines/fit_and_save_text_models.py, psycop/projects/clozapine/feature_generation/modules/text_model_pipelines/preprocess_sfis.py
Du må gerne kigge mest på cohort definition- koden. Features har jeg mest copy-paste fra tvang.
=> Clozapine cohort defintion

psycop/common/model_training_v2/loggers/base_logger.py, psycop/common/model_training_v2/pipeline.py, psycop/common/model_training_v2/training_method/base_training_method.py
- Squash changes from parent branch
- feat: add logger.info
=> feat: add logger.info()

psycop/common/model_training_v2/test_pipeline.py, psycop/common/model_training_v2/trainer/task/binary_classification/binary_classification.py, psycop/common/model_training_v2/trainer/task/test_binary_classification.py
=> fix: pass pred time uuid to binaryclassification task

psycop/common/test_utils/str_to_df.py
- feat: add support for spaces in header titles
- feat: support spaces within column names
=> feat: support spaces in col name lines for str_to_df

psycop/common/model_training_v2/hyperparameter_suggester/suggesters/logistic_regression_suggester.py, psycop/common/model_training_v2/hyperparameter_suggester/suggesters/test_suggesters.py, psycop/common/model_training_v2/hyperparameter_suggester/test_hyperparam_search.cfg, psycop/common/model_training_v2/trainer/task/estimator_steps/logistic_regression.py, psycop/common/model_training_v2/trainer/task/estimator_steps/test_logistic_regression.py
=> refactor: co-locate suggesters and their functions

psycop/common/model_training_v2/config/historical_registry_configs/preprocessing/column_exists_validator/column_exists_validator_20231115_152531.cfg, psycop/common/model_training_v2/config/historical_registry_configs/preprocessing/column_exists_validator/column_exists_validator_20231115_154049.cfg, psycop/common/model_training_v2/config/historical_registry_configs/preprocessing/column_exists_validator/column_exists_validator_20231115_154603.cfg, psycop/common/model_training_v2/config/populate_registry.py, psycop/common/model_training_v2/config/registries_testing_utils.py
- misc.
- misc.
- style: auto-fixes from pre-commit
- misc.
=> check registered functions can resolve

.vscode/tasks.json, Makefile, tasks.py
=> dev: update vscode test task

.vscode/tasks.json, Makefile, tasks.py
=> dev: add qtest and qlint

.vscode/settings.json
=> dev: change issue sort order

psycop/common/model_training_v2/test_pipeline.py, psycop/common/model_training_v2/trainer/cross_validator_trainer.py, psycop/common/model_training_v2/trainer/data/minimal_test_data.py, psycop/common/model_training_v2/trainer/task/binary_classification/binary_classification_task.py
=> fix: drop entity id column during stratified crossval

.github/workflows/snyk.yml, .github/workflows/static_type_checks.yml, .github/workflows/vulnerability_scan.yml, requirements.txt, tasks.py
snyk not part of dependencies?
=> feat: add snyk workflow

psycop/common/model_training_v2/config/historical_registry_configs/loggers/multi_logger/multi_logger_20231204_140335.cfg, psycop/common/model_training_v2/config/populate_registry.py, psycop/common/model_training_v2/loggers/multi_logger.py
=> fix: add multilogger to registry

psycop/common/model_training_v2/loggers/base_logger.py, psycop/common/model_training_v2/loggers/disk_logger.py, psycop/common/model_training_v2/loggers/multi_logger.py, psycop/common/model_training_v2/loggers/terminal_logger.py, psycop/common/model_training_v2/loggers/test_disk_logger.py
=> Fix: disklogger cfg saving

psycop/common/model_training_v2/loggers/disk_logger.py
=> fix: overwrite log on new run

psycop/common/model_training_v2/config/historical_registry_configs/preprocessing/window_filter/window_filter_20231211_123506.cfg, psycop/common/model_training_v2/trainer/preprocessing/steps/row_filters.py, psycop/common/model_training_v2/trainer/preprocessing/steps/test_row_filters.py
stab at implementing the lookahead/behind row filter in the v2 pipeline. started questioning whether the filtering was correct because the tests didn't behave as I expected (created an issue #531). not particularly elegant (especially the lazyframe vs dataframe handling), very open to comments
Attempts for fix #506.
=> add window row filter

psycop/projects/sequence_models/finetune_behrt_t2d-from-pretrain.cfg, psycop/projects/sequence_models/finetune_t2d.py
As far as I can tell, all we need is a path to the pretrained model, and then this should be ready to finetune!
=> feat: finetune trainer from pretrained checkpoint

requirements.txt
Vulnerability to directory traversal found in certain versions of mlflow (https://security.snyk.io/vuln/SNYK-PYTHON-MLFLOW-6128849). Can be fixed by upgrading to >=2.9.2.
=> fix critical vulnerability in mlflow

psycop/common/feature_generation/sequences/patient_loaders.py, psycop/common/feature_generation/sequences/patient_slice_getter.py, psycop/common/sequence_models/config_schema.py, psycop/common/sequence_models/embedders/BEHRT_embedders.py, psycop/common/sequence_models/registry.py, psycop/common/sequence_models/tests/test_config.cfg, psycop/common/sequence_models/tests/test_finetuning.cfg, psycop/common/sequence_models/tests/test_finetuning.py, psycop/common/sequence_models/tests/test_train.py, psycop/common/sequence_models/train.py, psycop/projects/sequence_models/finetune_behrt_t2d-no-pretrain.cfg, psycop/projects/sequence_models/finetune_t2d-debug.cfg, psycop/projects/sequence_models/finetune_t2d.py, psycop/projects/sequence_models/pretrain_behrt.cfg, psycop/projects/sequence_models/pretrain_mini_behrt.cfg, psycop/projects/t2d/feature_generation/cohort_definition/t2d_cohort_definer.py
Depends on #566, review that first.
It works!
=> feat: first mlflow pretraining

psycop/common/data_structures/prediction_time.py, psycop/common/feature_generation/sequences/prediction_time_collater.py, psycop/common/sequence_models/__init__.py, psycop/common/sequence_models/apply.py, psycop/common/sequence_models/config_schema.py, psycop/common/sequence_models/tasks/__init__.py, psycop/common/sequence_models/tasks/patientslice_classifier.py, psycop/common/sequence_models/tasks/patientslice_classifier_base.py, psycop/common/sequence_models/tests/conftest.py, psycop/common/sequence_models/tests/test_apply.py, psycop/common/sequence_models/tests/test_encoder_for_clf.py, psycop/common/sequence_models/tests/test_finetuning.py, psycop/common/sequence_models/train.py
=> feat: add apply step to seq models

psycop/projects/scz_bp/data_inspection/age_at_outcome.py, psycop/projects/scz_bp/data_inspection/first_lithium_use.py, psycop/projects/scz_bp/data_inspection/scz_bp_age_at_outcome.py, psycop/projects/scz_bp/data_inspection/scz_bp_time_of_first_contact_to_outcome.py, psycop/projects/scz_bp/feature_generation/eligible_prediction_times/check_age_distribution.py, psycop/projects/scz_bp/feature_generation/eligible_prediction_times/scz_bp_eligible_config.py, psycop/projects/scz_bp/feature_generation/eligible_prediction_times/scz_bp_prediction_time_loader.py, psycop/projects/scz_bp/feature_generation/eligible_prediction_times/single_filters.py, psycop/projects/scz_bp/feature_generation/outcome_specification/add_time_from_first_visit.py, psycop/projects/scz_bp/feature_generation/outcome_specification/first_scz_or_bp_diagnosis.py
=> Scz bp eval

.devcontainer/devcontainer.json
=> feat: remove unused extensions

.devcontainer/devcontainer.json, .vscode/tasks.json, dev-requirements.txt
=> dev: try out herbarium

psycop/common/model_training_v2/loggers/mlflow_logger.py, psycop/common/sequence_models/train.py
=> feat: sanitise dict keys for mlflow

psycop/common/types/test_validated_frame.py, psycop/common/types/validated_frame.py
=> fix: column name is inferred from attr, not string for ValidatedFrame (issue #633)

psycop/common/feature_generation/sequences/patient_loader.py, psycop/common/feature_generation/sequences/patient_slice_collater.py, psycop/common/feature_generation/sequences/prediction_time_collater.py, psycop/common/feature_generation/sequences/prediction_times_from_cohort.py, psycop/common/types/test_validated_frame.py
=> feat: use SplitIDs for splits  (issue #593)

.vscode/tasks.json
=> dev: default task should not push or pull

psycop/common/global_utils/synth_data_generator/synth_col_generators.py, psycop/common/model_training_v2/trainer/preprocessing/pipeline.py, psycop/common/model_training_v2/trainer/preprocessing/step.py, psycop/common/model_training_v2/trainer/preprocessing/steps/cell_transformers.py, psycop/common/model_training_v2/trainer/preprocessing/steps/column_filters.py, psycop/common/model_training_v2/trainer/preprocessing/steps/column_validator.py, psycop/common/model_training_v2/trainer/preprocessing/steps/row_filters.py, psycop/common/model_training_v2/trainer/preprocessing/steps/test_cell_transformers.py, psycop/common/model_training_v2/trainer/preprocessing/steps/test_column_filters.py, psycop/common/model_training_v2/trainer/preprocessing/steps/test_row_filters.py
=> refactor(#648): presplitsteps-should-only-take-lazyframes

psycop/common/feature_generation/sequences/prediction_times_from_cohort.py, psycop/common/model_training_v2/config/historical_registry_configs/data/filtered_dataloader/filtered_dataloader_20231128_123930.cfg, psycop/common/model_training_v2/config/historical_registry_configs/data_filters/regional_data_filter/regional_data_filter_20231128_123930.cfg, psycop/common/model_training_v2/config/historical_registry_configs/data_filters/regional_data_filter/regional_data_filter_20240110_093403.cfg, psycop/common/model_training_v2/trainer/data/data_filters/geography.py, psycop/common/model_training_v2/trainer/data/data_filters/test_data_filters.py
=> feat(#656): RegionalFilter-can-take-classical-split-names-train/test/val

psycop/common/model_training_v2/config/test_registry_resolution.py
=> fix(#671): improve-error-when-cannot-parse-registered-config

.github/workflows/periodical_vulnerability_scan.yml, .github/workflows/type_check.yml, .vscode/tasks.json, tasks.py
=> dev(#670): prompt-to-submit-if-all-tests-pass

tasks.py
=> dev(#680): make-type-checking-optional

.vscode/tasks.json, tasks.py
=> dev(#684): prettier-message-when-skipping-types

psycop/common/model_training_v2/config/historical_registry_configs/preprocessing/quarantine_filter/quarantine_filter_20240115_120142.cfg, psycop/common/model_training_v2/config/historical_registry_configs/preprocessing/washout_filter/washout_filter_20240115_105320.cfg, psycop/common/model_training_v2/config/test_registry_resolution.py, psycop/common/model_training_v2/trainer/preprocessing/steps/row_filter_other.py, psycop/common/model_training_v2/trainer/preprocessing/steps/test_row_filters.py
=> perf(#599): reimplement quarantine_filter for lazyframes

psycop/projects/scz_bp/feature_generation/scz_bp_embed_text.py
=> feat(#687): embed-text-with-multiple-embedding-models

psycop/projects/scz_bp/feature_generation/text_experiment/scz_bp_text_experiment_feature_gen.py
=> scz_bp: create-features-for-text-experiment

psycop/automation/git.py, psycop/automation/lint.py, psycop/projects/scz_bp/feature_generation/inspect_feature_sets.py
=> fix(#697): pylance-errors-that-show-up-on-my-machine-but-not-Martins-🤷‍♂️

requirements.txt
=> added_rapidfuzz_package_to_requirements

psycop/common/feature_generation/sequences/patient_loader.py, psycop/common/sequence_models/embedders/BEHRT_embedders.py, psycop/common/sequence_models/train.py, psycop/projects/sequence_models/pretrain_behrt.cfg
=> refactor: tiny misc.

psycop/common/model_training_v2/trainer/preprocessing/steps/row_filter_split.py, psycop/common/sequence_models/registry.py, psycop/common/sequence_models/train.py, psycop/projects/sequence_models/pretrain_behrt.cfg
=> feat: working pretraining

tasks.py
=> fix(#720): do not require questionary for tasks.py

psycop/common/model_training_v2/loggers/mlflow_logger.py
=> feat(#690): write config to mlflow as artifact

.github/workflows/periodical_vulnerability_scan.yml, .github/workflows/type_check.yml
=> ci: remove questionary install

.vscode/tasks.json
=> dev(#728): update tasks.json with new herb vocab

psycop/common/types/test_validated_frame.py, psycop/common/types/validated_frame.py
=> allow extra columns fix

psycop/common/model_training_v2/trainer/cross_validator_trainer.py, psycop/common/model_training_v2/trainer/split_trainer.py, psycop/projects/scz_bp/evaluation/scz_bp_run_evaluation_suite.py
=> refactor: turn trainers into dataclasses

psycop/common/model_training_v2/loggers/base_logger.py, psycop/common/model_training_v2/loggers/disk_logger.py, psycop/common/model_training_v2/loggers/mlflow_logger.py, psycop/common/model_training_v2/loggers/multi_logger.py, psycop/common/model_training_v2/loggers/terminal_logger.py, psycop/common/model_training_v2/loggers/test_disk_logger.py
=> feat: add log_artifact

psycop/common/model_training_v2/loggers/terminal_logger.py, psycop/common/model_training_v2/test_pipeline.py, psycop/common/model_training_v2/trainer/base_trainer.py, psycop/common/model_training_v2/trainer/cross_validator_trainer.py, psycop/common/model_training_v2/trainer/split_trainer.py
=> feat: trainers should log sklearn_pipes

dev-requirements.txt
=> dev: use lumberman

.devcontainer/devcontainer.json
=> dev: add auto commit gen

.vscode/tasks.json
=> dev: fix tasks.json

psycop/common/model_training_v2/hyperparameter_suggester/suggesters/suggester_spaces.py, psycop/common/model_training_v2/trainer/task/estimator_steps/logistic_regression.py, psycop/common/model_training_v2/trainer/task/estimator_steps/test_suggesters.py
=> feat(#713): shorthand for constructing floatspaces

psycop/common/model_training_v2/config/baseline_test_config.cfg, psycop/common/model_training_v2/test_pipeline.py, psycop/common/model_training_v2/trainer/cross_validator_trainer.py, psycop/common/model_training_v2/trainer/preprocessing/pipeline.py
=> feat(#736): log which columns are used during training

psycop/common/model_training_v2/loggers/mlflow_logger.py
=> fix(#748): mlflow creates new logging file for each logging operation

psycop/common/model_training_v2/config/historical_registry_configs/loggers/mlflow_logger/mlflow_logger_20231228_135021.cfg, psycop/common/model_training_v2/loggers/mlflow_logger.py
=> fix: create new run for each mlflowlogger init

.vscode/tasks.json
=> dev(#756): squash on submit

requirements.txt
=> dev(#763): update timeseriesflattener for pydantic 2.0

psycop/projects/cvd/feature_generation/feature_layeres/base.py, psycop/projects/cvd/feature_generation/feature_layeres/layer_1.py, psycop/projects/cvd/feature_generation/feature_layeres/layer_2.py, psycop/projects/cvd/feature_generation/feature_layeres/layer_3.py, psycop/projects/cvd/feature_generation/main.py, psycop/projects/cvd/feature_generation/specify_features.py
=> exp: generate CVD features

psycop/common/model_training_v2/loggers/mlflow_logger.py
=> feat: do not init mlflow until first logging operation

psycop/common/model_training_v2/config/baseline_pipeline.py, psycop/common/model_training_v2/config/historical_registry_configs/preprocessing/column_exists_validator/column_exists_validator_20231124_080137.cfg, psycop/common/model_training_v2/config/historical_registry_configs/preprocessing/column_prefix_count_expectation/column_prefix_count_expectation_20231124_080137.cfg, psycop/common/model_training_v2/trainer/preprocessing/steps/column_validator.py, psycop/common/model_training_v2/trainer/preprocessing/steps/test_column_validator.py
=> refactor: avoid unneeded variadic arguments in preprocessing

psycop/common/model_training_v2/trainer/cross_validator_trainer.py, psycop/common/model_training_v2/trainer/preprocessing/steps/column_filters.py, psycop/projects/cvd/model_training/cvd_baseline.cfg, psycop/projects/cvd/model_training/train_model_e2e_v2.py
=> exp(#762): generate t2d feature set for level 4 x [mean, min, max, count, bool]

psycop/common/model_training_v2/loggers/terminal_logger.py
=> feat(#772): use rich for pretty printing in terminallogger

psycop/projects/cvd/feature_generation/feature_layeres/base.py, psycop/projects/cvd/feature_generation/feature_layeres/layer_1.py, psycop/projects/cvd/feature_generation/feature_layeres/layer_2.py, psycop/projects/cvd/feature_generation/feature_layeres/layer_3.py, psycop/projects/cvd/feature_generation/main.py, psycop/projects/cvd/feature_generation/specify_features.py, psycop/projects/cvd/model_training/cvd_baseline.cfg
=> feat: try different lookbehinds

.vscode/tasks.json
=> dev: run tests on submit

psycop/common/model_training/config_schemas/preprocessing.py, psycop/projects/forced_admission_inpatient/model_eval/model_description/performance/cross_validation_performance_table.py, psycop/projects/forced_admission_inpatient/model_eval/model_permuation/train_test_different_lookaheads.py
Also fixes minor bug induced by pydantic update
=> fa_inpatient: add cv performance table

psycop/common/model_training_v2/trainer/split_trainer.py
=> use val y for result metric

psycop/common/model_training_v2/hyperparameter_suggester/suggesters/suggester_spaces.py
=> feat: add integerspace

psycop/common/model_training_v2/config/historical_registry_configs/estimator_steps/lightgbm/lightgbm_20240131_114833.cfg, psycop/common/model_training_v2/config/historical_registry_configs/estimator_steps/xgboost/xgboost_20240131_115154.cfg, psycop/common/model_training_v2/config/historical_registry_configs/estimator_steps/xgboost/xgboost_20240131_115217.cfg, psycop/common/model_training_v2/config/historical_registry_configs/estimator_steps_suggesters/xgboost_suggester/xgboost_suggester_20240131_114833.cfg, psycop/common/model_training_v2/config/historical_registry_configs/estimator_steps_suggesters/xgboost_suggester/xgboost_suggester_20240131_114956.cfg, psycop/common/model_training_v2/hyperparameter_suggester/suggesters/suggester_spaces.py, psycop/common/model_training_v2/trainer/task/estimator_steps/test_suggesters.py, psycop/common/model_training_v2/trainer/task/estimator_steps/xgboost.py
=> feat: xgboost suggester

psycop/common/model_training_v2/config/historical_registry_configs/estimator_steps/lightgbm/lightgbm_20240131_141559.cfg, psycop/common/model_training_v2/config/historical_registry_configs/estimator_steps/xgboost/xgboost_20240131_141311.cfg, psycop/common/model_training_v2/config/historical_registry_configs/estimator_steps/xgboost/xgboost_20240131_141559.cfg, psycop/common/model_training_v2/config/historical_registry_configs/estimator_steps_suggesters/lightgbm_suggester/lightgbm_suggester_20240131_141311.cfg, psycop/common/model_training_v2/trainer/task/estimator_steps/lightgbm.py, psycop/common/model_training_v2/trainer/task/estimator_steps/test_suggesters.py
=> feat: lightgbm suggester

.devcontainer/devcontainer.json, gpu-requirements.txt, synthcity-reqs.txt
=> fix(#802): vulnerability scan failed

psycop/common/global_utils/mlflow/mlflow_data_extraction.py, psycop/projects/scz_bp/text_experiment/mlflow_data_extraction.py
Wanted to create a cute little table of performances from my text experiment, but turned out to be more painful than expected to interface with mlflow. Created this little class to help. 
Very open for comments, especially on naming and placement in the repo
=> feat: extract metrics from mlflow 

psycop/projects/scz_bp/text_experiment/scz_bp_text_performance_table.py
=> sczbp: add text performance table

psycop/common/model_training_v2/config/historical_registry_configs/estimator_steps/xgboost/xgboost_20240213_112404.cfg, psycop/common/model_training_v2/trainer/preprocessing/pipeline.py
=> add row count to train pipeline

psycop/common/feature_generation/text_models/count_keyword.py, psycop/common/feature_generation/text_models/pse_keywords.yaml
=> feat: add pse keyword count embedding

psycop/common/feature_generation/application_modules/chunked_feature_generation.py, psycop/common/feature_generation/application_modules/flatten_dataset.py, psycop/common/feature_generation/application_modules/generate_feature_set.py, psycop/common/feature_generation/application_modules/test_chunked_feature_generation.py, psycop/common/feature_generation/loaders/raw/load_text.py, psycop/common/model_training_v2/trainer/task/base_task.py, psycop/projects/cancer/feature_generation/main.py, psycop/projects/cancer/main.py, psycop/projects/cvd/feature_generation/main.py, psycop/projects/forced_admission_inpatient/feature_generation/main.py, psycop/projects/restraint/feature_generation/main.py, psycop/projects/scz_bp/feature_generation/scz_bp_generate_features.py, psycop/projects/scz_bp/text_experiment/feature_gen/scz_bp_text_experiment_generate_features.py, psycop/projects/t2d/feature_generation/lookbehind_experiment/generate_features.py, psycop/projects/t2d/feature_generation/main.py, psycop/projects/t2d/main.py
Focus on `generate_feature_set.py` :)
=> feat(#825):  feature generation using timeseriesflattener v2

psycop/projects/forced_admission_inpatient/model_eval/model_description/performance/cross_validation_performance_table.py
=> fa-fix cross val table

psycop/common/feature_generation/loaders/raw/load_procedures.py, psycop/common/feature_generation/text_embeddings/embed_text_with_sent_transformers.py, psycop/common/feature_generation/text_models/count_keyword.py, psycop/common/feature_generation/text_models/encode_text_as_tfidf_scores.py, psycop/common/model_training_v2/config/historical_registry_configs/data/mock_regional_move_df/mock_regional_move_df_20231128_124908.cfg, psycop/common/model_training_v2/config/historical_registry_configs/estimator_steps/xgboost/xgboost_20240227_094854.cfg, psycop/common/model_training_v2/config/populate_registry.py, psycop/common/model_training_v2/trainer/preprocessing/steps/column_filters.py, psycop/common/model_training_v2/trainer/preprocessing/steps/row_filter_split.py, psycop/common/model_training_v2/trainer/preprocessing/steps/test_row_filter_split.py, psycop/projects/scz_bp/text_experiment/feature_gen/scz_bp_embed_text_with_tfidf.py, psycop/projects/scz_bp/text_experiment/feature_gen/scz_bp_embed_text_with_transformers.py, requirements.txt
=> deps: upgrade polars to 0.20.10

psycop/projects/t2d/paper_outputs/dataset_description/by_outcome/descriptive_stats_by_outcome.py
=> feat: create descriptive_stats_by_outcome.py

psycop/common/model_evaluation/binary/performance_by_ppr/performance_by_ppr.py, psycop/projects/t2d/paper_outputs/dataset_description/by_outcome/descriptive_stats_by_outcome.py, psycop/projects/t2d/paper_outputs/model_description/performance/performance_by_ppr.py, psycop/projects/t2d/paper_outputs/model_description/performance/test_t2d_performance_by_ppr.py, pyproject.toml
=> feat(#834): t2d add MCC and F1 to results table

psycop/common/model_training_v2/loggers/base_logger.py, psycop/common/model_training_v2/loggers/disk_logger.py, psycop/common/model_training_v2/loggers/dummy_logger.py, psycop/common/model_training_v2/loggers/mlflow_logger.py, psycop/common/model_training_v2/loggers/multi_logger.py, psycop/common/model_training_v2/loggers/terminal_logger.py, psycop/common/model_training_v2/trainer/cross_validator_trainer.py, psycop/common/model_training_v2/trainer/split_trainer.py
=> feat(#847): log_dataset

psycop/projects/forced_admission_inpatient/model_eval/config.py, psycop/projects/forced_admission_inpatient/model_eval/model_description/performance/cost_benefit_plots.py, psycop/projects/forced_admission_inpatient/model_eval/model_description/performance/performance_by_ppr.py, psycop/projects/forced_admission_inpatient/model_eval/model_description/performance/sensitivity_by_time_to_event.py
Update perfomance table with F1 and MCC scores
=> fai: update perf table

psycop/common/model_training_v2/hyperparameter_suggester/optuna_hyperparameter_search.py
=> fix: study creation before parallelization

psycop/common/model_training_v2/trainer/task/estimator_steps/lightgbm.py, psycop/projects/scz_bp/evaluation/figure2/first_positive_prediction_to_outcome.py, psycop/projects/scz_bp/evaluation/figure3/figure_3_panels.py, psycop/projects/scz_bp/evaluation/model_performance/feature_importance/scz_bp_gain.py, psycop/projects/scz_bp/evaluation/model_performance/robustness/scz_bp_robustness_by_age.py, psycop/projects/scz_bp/evaluation/model_performance/robustness/scz_bp_robustness_by_calendar_time.py, psycop/projects/scz_bp/evaluation/model_performance/robustness/scz_bp_robustness_by_cyclic_time.py, psycop/projects/scz_bp/evaluation/model_performance/robustness/scz_bp_robustness_by_sex.py, psycop/projects/scz_bp/evaluation/model_performance/robustness/scz_bp_robustness_by_time_from_first_visit.py, psycop/projects/scz_bp/evaluation/model_performance/robustness/scz_bp_robustness_plot.py, psycop/projects/scz_bp/model_training/config/scz_bp_structured_only.cfg, psycop/projects/scz_bp/model_training/config/scz_bp_structured_text.cfg, psycop/projects/scz_bp/model_training/hparam_search_scz_bp.py
=> sczbp: fig 2

psycop/common/model_training_v2/loggers/mlflow_logger.py
=> feat: upload pred df to mlflow

psycop/projects/clozapine/model_eval/model_description/performance/confusion_matrix_pipeline.py, psycop/projects/clozapine/model_eval/model_description/performance/cross_validation_performance_table.py, psycop/projects/clozapine/model_eval/table_one/table_one.py
=> Clozapine table 1

psycop/projects/cvd/cohort_examination/ldl_sampling.py, psycop/projects/cvd/cohort_examination/notebooks/ldl_sampling.py, pyproject.toml
=> feat: examine LDL sampling

psycop/common/feature_generation/application_modules/generate_feature_set.py, psycop/projects/bipolar/cohort_definition/bipolar_cohort_definition.py, psycop/projects/bipolar/feature_generation/bp_generate_features.py, psycop/projects/bipolar/feature_generation/bp_specify_features.py, psycop/projects/bipolar/feature_generation/feature_layers/bp_feature_layer.py, psycop/projects/bipolar/feature_generation/feature_layers/bp_layer_1.py, psycop/projects/bipolar/feature_generation/feature_layers/bp_layer_2.py, psycop/projects/bipolar/feature_generation/feature_layers/bp_layer_3.py, psycop/projects/bipolar/feature_generation/feature_layers/bp_layer_4.py, psycop/projects/bipolar/feature_generation/feature_layers/value_specification.py, psycop/projects/bipolar/feature_generation/inspect_feature_sets.py, psycop/projects/bipolar/patient_representations/pca.py, psycop/projects/bipolar/patient_representations/visualisations/trajectories.py, psycop/projects/bipolar/synthetic_data/bp_synthetic_data.py, psycop/projects/forced_admission_inpatient/model_eval/model_permuation/train_test_different_lookaheads.py, requirements.txt
bp: add features, pca, and trajectory plots
=> bp: add features, pca, and trajectory plots

requirements.txt
=> build: update tsflattener

psycop/common/model_training_v2/trainer/selective_cross_validator_trainer.py
=> fix: preprocess additinoal data in selective cv

psycop/common/model_training_v2/hyperparameter_suggester/optuna_hyperparameter_search.py
Necessary if one has registered project-specific functions (that should be added to the global registry, e.g. synthetic data) and want to do hparam search on configs including those functions
=> feat: allow passing custom populate registry fn to hparam search

psycop/common/global_utils/mlflow/mlflow_data_extraction.py
Small change, hope it's OK with a check for style :-)
=> feat: mlflow query for run and get eval_df

psycop/common/model_training_v2/hyperparameter_suggester/optuna_hyperparameter_search.py
=> feat: log trial number when hyperparameter tuning

psycop/common/model_training_v2/trainer/preprocessing/pipeline.py
=> feat: improve readability of logging

psycop/common/model_training_v2/loggers/mlflow_logger.py
=> feat: allow logging mlflow run name

README.md
=> feat: release please

psycop/projects/scz_bp/data_inspection/scz_bp_age_at_outcome.py, psycop/projects/scz_bp/data_inspection/scz_bp_incidence_by_date.py
=> sczbp: incidence by cal time

dev-requirements.txt
=> ci: update pyright

.snyk, requirements.txt
Updates to mitigate vulnerabilities caught be periodical snyk scans 
Fixes: #978 #982 #984 #974 #983
=> chore: fix snyk vulnerabilities (setuptools mm.)

.gitignore
=> add *.ipynb to .gitignore

psycop/common/model_training_v2/trainer/preprocessing/steps/row_filter_other.py, psycop/common/model_training_v2/trainer/preprocessing/steps/test_row_filters.py, psycop/common/model_training_v2/trainer/split_trainer.py, psycop/projects/t2d_extended/model_training/temporal_2021.py
Vi simulerer, at vi står i 2016-01-01 og træner en model på historiske data. Hvor godt vil den så klare sig fremadrettet?
AUROC evalueret på:
2016: 0.87
2017: 0.84
2018: 0.80
2019: 0.81
Hvis vi har meget tunge pipelines, kan vi nemt lave en version der bruger vores "splittrainer", men tager en allerede trænet pipeline.
=> feat: t2d temporal crossval for 2021

.github/workflows/periodical_vulnerability_scan.yml
=> ci: do not assign alumni

gpu-requirements.txt
=> fix: update sentence-transformers to fix vulnerability

psycop/projects/clozapine/feature_generation/cohort_definition/eligible_prediction_times/add_age.py, psycop/projects/clozapine/feature_generation/cohort_definition/eligible_prediction_times/prevalent_serum_clozapine.py, psycop/projects/clozapine/feature_generation/cohort_definition/eligible_prediction_times/schizophrenia_diagnosis.py, psycop/projects/clozapine/feature_generation/cohort_definition/outcome_specification/first_clozapine_prescription.py, psycop/projects/clozapine/feature_generation/cohort_definition/outcome_specification/visualization/combined_clozapine_visualization.py, psycop/projects/clozapine/loaders/coercion.py, psycop/projects/clozapine/loaders/demographics.py, psycop/projects/clozapine/loaders/diagnoses.py, psycop/projects/clozapine/loaders/lab.py, psycop/projects/clozapine/loaders/medications.py, psycop/projects/clozapine/loaders/structured_sfi.py, psycop/projects/clozapine/loaders/text.py, psycop/projects/clozapine/loaders/visits.py, psycop/projects/clozapine/model_training/hyperparam.py
=> Clozapine add loaders

psycop/projects/AcuteSomaticAdmission/CohortDefinition/Somatic_admission_cohort_definition.py, psycop/projects/AcuteSomaticAdmission/CohortDefinition/add_age.py, psycop/projects/AcuteSomaticAdmission/CohortDefinition/eligible_config.py, psycop/projects/AcuteSomaticAdmission/CohortDefinition/get_psychiatric_outpatient_visits.py, psycop/projects/AcuteSomaticAdmission/CohortDefinition/get_somatic_emergency_visits.py, psycop/projects/AcuteSomaticAdmission/CohortDefinition/single_filters.py
=> cohort definition

psycop/projects/AcuteSomaticAdmission/Evaluation/dataset_evaluation, psycop/projects/AcuteSomaticAdmission/Evaluation/dataset_evaluation.py
=> Evaluering

psycop/common/feature_generation/loaders/raw/load_structured_sfi.py, psycop/projects/AcuteSomaticAdmission/Evaluation/dataset_evaluation, psycop/projects/AcuteSomaticAdmission/FeatureGeneration/Main.py, psycop/projects/AcuteSomaticAdmission/FeatureGeneration/Main_oldVersion, psycop/projects/AcuteSomaticAdmission/FeatureGeneration/modules/specify_features.py, psycop/projects/AcuteSomaticAdmission/FeatureGeneration/modules/specify_text_features.py, psycop/projects/AcuteSomaticAdmission/FeatureGeneration/modules/text_model_pipelines/fit_and_save_text_models.py, psycop/projects/AcuteSomaticAdmission/FeatureGeneration/modules/text_model_pipelines/preprocess_sfis.py, psycop/projects/AcuteSomaticAdmission/FeatureGeneration/modules/utils.py
=> FeatureGeneration

psycop/projects/AcuteSomaticAdmission/model_training/hyperparam_tune_somatic_model.py, psycop/projects/AcuteSomaticAdmission/model_training/populate_somatic_registry.py, psycop/projects/AcuteSomaticAdmission/model_training/somatic_crossval.cfg, psycop/projects/AcuteSomaticAdmission/model_training/somatic_hyperparam.cfg, psycop/projects/AcuteSomaticAdmission/model_training/train_somatic_model.py
=> model-training

psycop/projects/AcuteSomaticAdmission/CohortDefinition/Somatic_admission_cohort_definition.py, psycop/projects/AcuteSomaticAdmission/CohortDefinition/get_psychiatric_outpatient_visits.py
=> cohort definition fix panda to polar

psycop/projects/AcuteSomaticAdmission/FeatureGeneration/Main.py, psycop/projects/AcuteSomaticAdmission/model_training/hyperparam_tune_somatic_model.py, psycop/projects/AcuteSomaticAdmission/model_training/somatic_hyperparam.cfg
=> Hyperparam tune

psycop/projects/clozapine/loaders/ect.py
=> added ect-loader

psycop/projects/clozapine/feature_generation/modules/specify_features.py
=> specify_features_changes

requirements.txt
=> chore/snyk: update timeseriesflattener and mlflow 

psycop/common/feature_generation/loaders/raw/utils.py, psycop/projects/clozapine/feature_generation/modules/specify_features.py, psycop/projects/clozapine/loaders/diagnoses.py, psycop/projects/clozapine/loaders/medications.py
=> added-unique-count-argument-to-load-from-codes

psycop/projects/clozapine/feature_generation/clozapine_generate_features.py, psycop/projects/clozapine/feature_generation/cohort_definition/eligible_prediction_times/prevalent_serum_clozapine.py, psycop/projects/clozapine/feature_generation/feature_layers/clozapine_feature_layer.py, psycop/projects/clozapine/feature_generation/feature_layers/clozapine_layer_1.py, psycop/projects/clozapine/feature_generation/feature_layers/clozapine_layer_2.py, psycop/projects/clozapine/feature_generation/feature_layers/clozapine_layer_3.py, psycop/projects/clozapine/feature_generation/feature_layers/clozapine_layer_4.py, psycop/projects/clozapine/feature_generation/feature_layers/value_specification.py, psycop/projects/clozapine/feature_generation/v1_main.py, psycop/projects/clozapine/feature_generation/v1_modules/specify_features.py, psycop/projects/clozapine/feature_generation/v1_modules/specify_text_features.py, psycop/projects/clozapine/loaders/coercion.py, psycop/projects/clozapine/loaders/lab_results.py, psycop/projects/clozapine/loaders/medications.py
=> migration-to-v2-feature-gen

psycop/projects/clozapine/feature_generation/clozapine_generate_features.py, psycop/projects/clozapine/feature_generation/clozapine_generate_only_text_features.py
=>  adjustments-to-v2-feature-gen-clozapine

.github/workflows/review_checklist.yml, README.md
=> test security checklist

psycop/common/global_utils/sql/get_sql_table_names.py
=> fixed_function_name_for_get_sql_table_names

psycop/projects/clozapine/feature_generation/clozapine_generate_features.py, psycop/projects/clozapine/feature_generation/cohort_definition/clozapine_cohort_definition.py, psycop/projects/clozapine/loaders/medications.py
=> add-fast-antipsychotics-as-features

psycop/projects/clozapine/loaders/text.py, psycop/projects/clozapine/text_models/fit_and_save_TFIDF_model.py, psycop/projects/clozapine/text_models/preprocessing.py, psycop/projects/clozapine/text_models/utils.py
=> clozapine-text-pipeline-adjustments

psycop/projects/clozapine/feature_generation/clozapine_generate_baseline_feature_set.py, psycop/projects/clozapine/feature_generation/clozapine_generate_features.py, psycop/projects/clozapine/loaders/text.py, psycop/projects/clozapine/text_models/fit_and_save_TFIDF_model.py, psycop/projects/clozapine/text_models/preprocessing.py, psycop/projects/clozapine/text_models/text_model_pipeline.py
=> Clozapine text fixes

psycop/projects/clozapine/feature_generation/clozapine_generate_baseline_feature_set.py, psycop/projects/clozapine/feature_generation/clozapine_generate_features.py, psycop/projects/clozapine/feature_generation/cohort_definition/eligible_prediction_times/eligible_config.py, psycop/projects/clozapine/text_models/fit_and_save_TFIDF_model.py, psycop/projects/clozapine/text_models/text_model_pipeline.py
=> Clozapine text and features fix

psycop/projects/clozapine/feature_generation/clozapine_generate_baseline_feature_set.py, psycop/projects/clozapine/feature_generation/clozapine_generate_features.py, psycop/projects/clozapine/loaders/ect.py
=> add ect as predictor

psycop/projects/scz_bp/evaluation/figure2/first_positive_prediction_to_outcome.py, psycop/projects/scz_bp/evaluation/scz_bp_run_evaluation_suite.py, psycop/projects/scz_bp/evaluation/table2/performance_by_ppr.py, psycop/projects/scz_bp/model_training/config/test_set/structured_text_ddpm_crossval.cfg, psycop/projects/scz_bp/model_training/config/test_set/text_only.cfg, psycop/projects/scz_bp/model_training/run_single_model.py
changes made to be able to rerun results, including loading eval ds from disk and adding disk logger
=> scz_bp rerun

.snyk, gpu-requirements.txt
=> fix transformer vulnerability

psycop/common/model_training_v2/test_pipeline.py, psycop/common/model_training_v2/trainer/cross_validator_trainer.py, psycop/common/model_training_v2/trainer/selective_cross_validator_trainer.py, psycop/common/model_training_v2/trainer/split_trainer.py
removed the option to provide a list of additional metrics. would be the optimal choice, but couldn't get it to work, so postponed that headache for when we'll need it
=> fix: additional metrics

psycop/projects/clozapine/loaders/text.py
=> add-psykiatri-konference-to-valid-text-sfi-names

psycop/projects/clozapine/model_eval/model_description/performance/cross_validation_performance_table.py
=> add-cross-val-table

psycop/projects/clozapine/cohort_examination/filtering_flowchart.py, psycop/projects/clozapine/model_eval/model_description/performance/cross_validation_performance_table.py, psycop/projects/clozapine/model_eval/table_one/facade.py
=> Clozapine new models with lookbehind filter

psycop/projects/clozapine/feature_generation/cohort_definition/outcome_specification/combine_text_structured_clozapine_outcome.py
=> add-print-numbers-outcome

.github/workflows/periodical_vulnerability_scan.yml
=> Remove assignee from vulnerability scan issue creation

psycop/projects/scz_bp/README.md
Update the scz-bp project metafile to include accurate details on model testing and resulting eval df
=> fix: update scz-bp metafile
